In [ ]:
import numpy as np

In [ ]:
#행렬의 요소의 인덱스를 입력하면, 그 요소의 [오른쪽, 위, 왼쪽, 아래]에 위치한 요소들의 인덱스를 반환하는 함수
#L=행렬의 행 길이, num=행렬에서 주위 이웃들을 찾고 싶은 요소의 위치(인덱스)
def neighbor(L,num):

  right = num+1
  if right % L == 0:
    right -= L

  left = num-1
  if (left+1) % L == 0:
    left += L

  up = num - L
  if up < 0:
    up += L*L

  down = num + L
  if down >= L*L:
    down -= L*L

  return np.array([right,up,left,down])

In [ ]:
print(np.array(range(5*5)).reshape(5,5), '\n') #이웃들을 확인하기 위해 임시로 만든 행렬

print('5x5행렬에서 인덱스14의 이웃들: ', neighbor(L=5,num=14))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

5x5행렬에서 인덱스14의 이웃들:  [10  9 13 19]


In [ ]:
#연결된 이웃들과 입력된 요소의 연결에 대한 에너지를 반환하는 함수
def neighbor_E(arr, L, num):
  return -np.sum(arr[neighbor(L,num)])*arr[num]

In [ ]:
#  neighbor_E을 이용하여 계산을 할, 행렬을 만들어야 한다.

#1또는 -1가 무작위로 채워진 5x5 행렬을 만드는 과정
L=5                                        # L 임의로 설정
random_arr = np.random.randn(L*L)          # 상태들의 분포 임의로 설정. +1과 -1이 50%확률로 선택되도록함. (radn에서 50% 확률로 음수인 수, 또는 양수인 수가 뽑힘 )
S = random_arr/abs(random_arr)             # (각 크기만큼 나누어서 크기를 모두 1로 맞춤)

print('1차원:\n', S, '\n')
print('2차원:\n', S.reshape(5,5))

1차원:
 [ 1. -1. -1.  1.  1. -1.  1.  1.  1.  1. -1.  1. -1.  1. -1. -1. -1.  1.
 -1. -1. -1. -1.  1. -1. -1.] 

2차원:
 [[ 1. -1. -1.  1.  1.]
 [-1.  1.  1.  1.  1.]
 [-1.  1. -1.  1. -1.]
 [-1. -1.  1. -1. -1.]
 [-1. -1.  1. -1. -1.]]


In [ ]:
E=0
for num in range(len(S)):#모든 "연결"에 관하여 계산한다
  E += (neighbor_E(S, L, num))
print('E =',E/2) #a에서 b의 계산은 b에서 a의 계산과 같으므로 (중복이 있기 때문에) 2로 나눈다.

E = -2.0


# 검증

In [ ]:
#neighbor_E를 통해 나온 결과가 정말 맞는 값인지 확인하고자 한다.

#L=2인 조건에서 직접 계산한 결과와 값이 똑같은지 비교하겠다.
L=2
S = np.array([-1,1,1,-1])
print(S.reshape(L,L),'\n')

E=0
for num in range(len(S)):
  E += (neighbor_E(S, L, num))

print('neighbor_E함수를 썼을 때:\n E =',E/2,'\n')
print('직접 계산했을 때:\n E =',(
-((-1)*(+1))-((-1)*(+1))-((-1)*(+1))-((-1)*(+1))
-((+1)*(-1))-((+1)*(-1))-((+1)*(-1))-((+1)*(-1))
-((+1)*(-1))-((+1)*(-1))-((+1)*(-1))-((+1)*(-1))
-((-1)*(+1))-((-1)*(+1))-((-1)*(+1))-((-1)*(+1))
)/2)

[[-1  1]
 [ 1 -1]] 

neighbor_E함수를 썼을 때:
 E = 8.0 

직접 계산했을 때:
 E = 8.0


In [ ]:
#또 다른 예
L=2
S = np.array([-1,1,-1,-1])
print(S.reshape(L,L),'\n')

E=0
for num in range(len(S)):
  E += (neighbor_E(S, L, num))

print('neighbor_E함수를 썼을 때:\n E =',E/2,'\n')
print('직접 계산했을 때:\n E =',(
-((-1)*(+1))-((-1)*(-1))-((-1)*(+1))-((-1)*(-1))
-((+1)*(-1))-((+1)*(-1))-((+1)*(-1))-((+1)*(-1))
-((-1)*(-1))-((-1)*(-1))-((-1)*(-1))-((-1)*(-1))
-((-1)*(-1))-((-1)*(+1))-((-1)*(-1))-((-1)*(+1))
)/2)

[[-1  1]
 [-1 -1]] 

neighbor_E함수를 썼을 때:
 E = 0.0 

직접 계산했을 때:
 E = 0.0
